Solved Merge Conflicts
rformassspectrometry/Deprecated-MsBackendSql pull request #10
Opened 2020-06-17 16:53 UTC by plantton

2020-06-22 16:52 UTC, jorainer commented
Does this include also PR#6 @plantton ?

2020-06-22 20:32 UTC, plantton commented
> Does this include also PR#6 @plantton ?

Yes. It contains PR#6.

2020-06-23 10:51 UTC, jorainer requested changes
Thanks for the PR @plantton ! I have only some questions and minor comments.

2020-06-23 10:51 UTC, jorainer commented on .github/workflows/check-standard.yaml
> +      - name: Install netcdf (macOS)
Just out of curiosity: is the `sysreqs` package not installing these by default?

2020-06-23 10:51 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +        i <- i2index(i, length(x), rownames(x@spectraData))
I'm confused - I thought that this backend does **not** store any data in the `x@spectraData` slot but retrieves also the metadata (i.e. the `x@spectraData`) from the database?

2020-06-23 10:51 UTC, jorainer commented on R/MsBackendSqlDb.R
> +#' - `@index` (`integer`): the index of the rows, which has been labelled by
Is this not redundant with `@rows`? I thought that in `@rows` you store the primary keys of the data and that filtering and subsetting changes these (also eventually re-ordering them)?

2020-06-23 10:51 UTC, jorainer commented on R/MsBackendSqlDb.R
> +                   query = "DBIResult",
Please also document this slot.

2020-06-23 10:51 UTC, jorainer commented on R/MsBackendSqlDb.R
> +                   index = "list"),
According to the documentation this is `integer` - please update/correct.

2020-06-23 10:51 UTC, jorainer commented on R/MsBackendSqlDb.R
> +    if (length(name) == 1) {
Can `$` really be called with a `name` of length > 1? I guess in most cases it will be just of length one, so I'm not sure if you really need the `if` `else` here.

2020-06-23 13:54 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +        i <- i2index(i, length(x), rownames(x@spectraData))
I just notice this PR also including the modifications from yesterday. There're still on the working progress. I will try to solve all the functions by these two days.

2020-06-26 17:36 UTC, lgatto commented
Careful, there are currently two PR, #10 (this one) and #6, but #6 has additional commit that are missing from this one. Both will need to be merged, hoping that no new conflicts will arise.

2020-06-26 19:38 UTC, plantton commented
> Careful, there are currently two PR, #10 (this one) and #6, but #6 has additional commit that are missing from this one. Both will need to be merged, hoping that no new conflicts will arise.

I will review them again.

2020-06-27 07:09 UTC, lgatto commented
> I will review them again.

Focus on one branch now to minimise further conflicts and I will merge both later.

2020-06-27 07:09 UTC, lgatto commented on .github/workflows/check-standard.yaml
> +      - name: Install netcdf (macOS)
Isn't this an `mzR` requirement?

2020-07-01 07:30 UTC, sgibb commented
While focusing on one branch would be useful I like to suggest to create smaller increment PRs. Reviewing these large nearly daily changing PRs is hard (and for me nearly impossible to follow/catch up).

2020-07-01 08:39 UTC, plantton commented
> While focusing on one branch would be useful I like to suggest to create smaller increment PRs. Reviewing these large nearly daily changing PRs is hard (and for me nearly impossible to follow/catch up).

Yes, indeed. Laurent also told me to send small PRs instead of a huge one. It would be really tough for reviewers. I will also send small PRs in future.

2020-07-01 09:55 UTC, lgatto commented
FYI: It looks like your `chmaster` branch (see PR #6) has been deleted.

2020-07-01 09:59 UTC, plantton commented
> FYI: It looks like your `chmaster` branch (see PR #6) has been deleted.

I actually didn't create this branch on my own repository. I want to focus on the `master` branch.

2020-07-01 10:45 UTC, lgatto commented on R/MsBackendSqlDb.R
> +                   index = "list"),
The `index` slot seems to have disapeared.

2020-07-01 10:46 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +        i <- i2index(i, length(x), rownames(x@spectraData))
This seems to be resolved.

2020-07-01 11:01 UTC, plantton commented on .github/workflows/check-standard.yaml
> +      - name: Install netcdf (macOS)
I added this dependencies since servers themselves don't contain this library. 

https://github.com/rformassspectrometry/MsBackendSql/issues/9#issue-632642019

2020-07-01 11:03 UTC, lgatto commented on R/MsBackendSqlDb.R
> +                   query = "DBIResult",
@plantton could you provide a description of that slot here please (as a reply to this comment), including a short description of why/how it is used/needed.

2020-07-01 11:19 UTC, merged