Add constructor for integration with Spectra
rformassspectrometry/Deprecated-MsBackendSql pull request #16
Opened 2020-07-06 13:02 UTC by plantton

This PR will add constructor of `MsBackendSqlDb`, for integration with `Spectra`. I also added documentation and unit tests.
This PR also corrects the issue #14, which can show an empty `MsBackendSqlDb` object properly now, unit tests are also added.

2020-07-07 06:29 UTC, jorainer requested changes
Nice PR @plantton . I just don't see the need to overwrite the `setMethod("Spectra", "character")` method from the `Spectra` package - I find this actually pretty problematic because it can lead to unexpected/unpredictable errors in future. I think we can get around this if you have a `backendInitialize` method for your backend that does not require a `dbcon` parameter, but uses the connection from the `@dbcon` slot. If this does not work I would rather change then the method in the `Spectra` package than overwriting it here.

2020-07-07 06:29 UTC, jorainer commented on R/MsBackendSqlDb.R
> +        spd <- asDataFrame(object, c("msLevel", "rtime", "scanIndex"))
Isn't `asDataFrame` getting the full data set (i.e. all rows)? Wouldn't it be better (faster) to just get the first 3 and last 3 rows instead of the full data?

2020-07-07 06:29 UTC, jorainer commented on R/MsBackendSqlDb.R
> +setMethod("Spectra",  "character",
I think we need to find a different solution than overwriting this method from the `Spectra` package. What is the reason that you need this method?

If it is *just* because you need a `dbcon` parameter to be passed to the `backendInitialize(source` call I think it would be better to change the `backendInitialize` method to use the `@dbcon` if no `dbcon` parameter is provided. That way you can directly use the `Spectra,"character"` method from the `Spectra` package. Also, have a look at the suggestion for the `MsBackendSQL()` constructor.  

```
...
if (missing(dbcon))
    dbcon <- object@dbcon
...
```

2020-07-07 06:29 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +    if (missing(dbcon))
Actually, if `dbcon` is missing, I would use a `dbConnect(SQLite(), tempfile())` instead. That way you have always a valid `dbcon` connection (see comment below for avoiding to overwrite the `setMethod("Spectra", "character")` method) - and the file would be deleted after closing R anyway.

2020-07-07 08:20 UTC, plantton commented on R/MsBackendSqlDb.R
> +        spd <- asDataFrame(object, c("msLevel", "rtime", "scanIndex"))
> Isn't `asDataFrame` getting the full data set (i.e. all rows)? Wouldn't it be better (faster) to just get the first 3 and last 3 rows instead of the full data?

Thanks. I completely ignored this problem. I will change it immediately.

2020-07-07 08:22 UTC, plantton commented on R/MsBackendSqlDb.R
> +setMethod("Spectra",  "character",
Indeed. I will modify the `backendInitialize` method, instead of overwriting `Spectra,"character"` method.

2020-07-07 08:23 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +    if (missing(dbcon))
Nice suggestions! Thank you!

2020-07-08 14:35 UTC, lgatto requested changes
Could you document how the `sciex_subset[1|2].[db|mzML]` files were created, ideally in a reproducible script such as  `inst/script/sciex_subset.R`.

2020-07-08 14:35 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +    if (!requireNamespace("DBI", quietly = TRUE))
Why is this check needed, given that `DBI` is a dependency?

2020-07-08 14:35 UTC, lgatto commented on R/MsBackendSqlDb.R
> +        cat(class(object), "with", length(object@rows), "spectra\n")
Here given that you know the length(object@row) is zero, print it out directly.

2020-07-08 14:35 UTC, lgatto commented on inst/scripts/TinySciex.R
> +out_file <- data.ramus <- "../extdata/sciex_subset1.mzML"
Could be consistent with variable naming and use `data_ramus` instead of `data.ramus` (and avoid using a `.` as a delimiter).

2020-07-08 16:25 UTC, plantton commented
> Could you document how the `sciex_subset[1|2].[db|mzML]` files were created, ideally in a reproducible script such as `inst/script/sciex_subset.R`.

I will do it.

2020-07-08 16:26 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +    if (!requireNamespace("DBI", quietly = TRUE))
I will remove it.

2020-07-22 15:49 UTC, plantton commented on R/MsBackendSqlDb.R
> +        cat(class(object), "with", length(object@rows), "spectra\n")
> length(object@row)

fixed in commit [14302f5](https://github.com/plantton/MsBackendSql/commit/14302f5359290a101634d631f7d95beb432610aa)

2020-07-30 14:27 UTC, jorainer requested changes
Some minor changes - and I think you did not address all comments from the original review?

2020-07-30 14:27 UTC, jorainer commented on R/MsBackendSqlDb.R
> +        spd <- asDataFrame(object, c("msLevel", "rtime", "scanIndex"))
I think you forgot to change that?

2020-07-30 14:27 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +.replace_db_table_columns <- function(x, name, value) {
Just for me to understand this: currently `update_db_table_columns` is used, but this would be an alternative implementation to achieve the same result, right?

2020-07-30 14:27 UTC, jorainer commented on vignettes/MsBackendSqlDb.Rmd
> +use non-parallel execution to create the new `Spectra` object:
I would the also write *the new `Spectra` object by specifying `BPPARAM = SerialParam()`:*

2020-07-30 14:42 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +.replace_db_table_columns <- function(x, name, value) {
> Just for me to understand this: currently `update_db_table_columns` is used, but this would be an alternative implementation to achieve the same result, right?

Indeed. `.replace_db_table_columns` isn't used in the current method, I kept it since this approach is faster on large SQL tables.

2020-07-30 14:47 UTC, plantton commented
> Some minor changes - and I think you did not address all comments from the original review?

How do you mean?

2020-07-30 15:19 UTC, plantton commented on R/MsBackendSqlDb.R
> +        spd <- asDataFrame(object, c("msLevel", "rtime", "scanIndex"))
> I think you forgot to change that?

No, it has been modified. The modified show method will only print the first and last 3 rows in the show method if the number of rows in MsBackendSqlDb is **larger than 10**. When the MsBackendSqlDb instance **has 0 rows** (empty but initialized backend), it will only print 0 rows in the result. Or else - **when MsBackendSqlDb instance has rows less or equal than 10**, it will fetch the result as a DFrame, and print the result. I think it would be ugly to print just 5 rows but with ellipsis inserted in the middle.

The show method will also print 0 instead of length(object@rows).

https://github.com/plantton/MsBackendSql/blob/master/R/MsBackendSqlDb.R#L123-L166

2020-07-30 16:13 UTC, jorainer commented on R/MsBackendSqlDb.R
> +        spd <- asDataFrame(object, c("msLevel", "rtime", "scanIndex"))
OK, sounds good - strange that the changes don't show up.

2020-07-30 16:15 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +.replace_db_table_columns <- function(x, name, value) {
OK, nice. Good to have it to be able to run benchmarks later.

2020-07-30 16:23 UTC, jorainer commented
@plantton I think it would be helpful if you address each comment in its separate commit and mention this commit in the comment. On my PR page it does for example not show that you addressed any of @lgatto 's comments - but maybe you have and that's now only a problem with this huge PR.

I think after this PR we should make sure to always aim for smaller PR.

2020-07-30 16:40 UTC, plantton commented
> @plantton I think it would be helpful if you address each comment in its separate commit and mention this commit in the comment. On my PR page it does for example not show that you addressed any of @lgatto 's comments - but maybe you have and that's now only a problem with this huge PR.
> 
> I think after this PR we should make sure to always aim for smaller PR.

Thank you for the tips. I also realized I have to put each commit related to a specific issue or bug.

2020-07-31 06:23 UTC, jorainer commented
@plantton , I was going through the vignette and am puzzled with the following: I was creating the backend as shown below and supposedly all the data should be stored in a *msdata.db* file, which was also created in the current directory **BUT** as you see below, the `@dbcon` of the backend points to another database

```r
conn <- dbConnect(SQLite(), "msdata.db")
sp_sql <- Spectra(fls, backend = MsBackendSqlDb(dbcon = conn),
                  BPPARAM = SerialParam())

sp_sql@backend@dbcon
<SQLiteConnection>
  Path: /tmp/Rtmphncgq2/file725700467.db
  Extensions: TRUE
```

This file in fact exists, and its size its twice the size of the *msdata.db* file. I think you might somewhere miss passing the initial `dbcon` from the constructor to some internal function?

2020-07-31 07:34 UTC, plantton commented
> @plantton , I was going through the vignette and am puzzled with the following: I was creating the backend as shown below and supposedly all the data should be stored in a _msdata.db_ file, which was also created in the current directory **BUT** as you see below, the `@dbcon` of the backend points to another database
> 
> ```r
> conn <- dbConnect(SQLite(), "msdata.db")
> sp_sql <- Spectra(fls, backend = MsBackendSqlDb(dbcon = conn),
>                   BPPARAM = SerialParam())
> 
> sp_sql@backend@dbcon
> <SQLiteConnection>
>   Path: /tmp/Rtmphncgq2/file725700467.db
>   Extensions: TRUE
> ```
> 
> This file in fact exists, and its size its twice the size of the _msdata.db_ file. I think you might somewhere miss passing the initial `dbcon` from the constructor to some internal function?

I will check it.

2020-08-04 06:44 UTC, jorainer requested changes
Thanks for fixing this @plantton . I have two comments/questions in the code and two additional things:

1) `dataStorage(sp_sql)` returns `"<db>"` while `sp_sql$dataStorage` returns the original values from the previous backend. Please change the content of the `"dataStorage"` column to `"<db>"` when you initialize the database.
2) remove the `filterIntensity` function. `filterIntensity` is a method for `Spectra` classes which is not supposed to be used by a backend. Please only implement methods listed in `MsBackend.R` in the `Spectra` package.

2020-08-04 06:44 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +        x@rows <- unlist(c(x@rows, seq_along(y@rows) + x_length))
Why do you need an `unlist` here? Wouldn't it be sufficient to just have the `c(...)`?

2020-08-04 06:44 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
>          x@modCount <- unlist(c(x@modCount, y@modCount),
Also here, I don't understand the `unlist`. Secondly, shouldn't `modCount` be a single `integer`? Here you are concatenating the `modCount` of `x` and `y` and you would get an integer of length 2. Maybe use `max(x@modCount, y@modCount)` instead to use the maximal mod count?

2020-08-04 07:13 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +        x@rows <- unlist(c(x@rows, seq_along(y@rows) + x_length))
I see. I will remove `filterIntensity` method and change the initialized values of "dataStorage".

2020-08-04 11:04 UTC, jorainer commented
Thanks for the update @plantton . Please also address my `unlist` and `@modCount` comments above - or let me know if I'm wrong there.

2020-08-04 18:33 UTC, plantton commented on R/MsBackendSqlDb-functions.R
>          x@modCount <- unlist(c(x@modCount, y@modCount),
I checked the `modCount` values in `MsBackendHdf5Peaks` backend, since I think `modCount` values shall be functional in the same way for `MsBackendSql`. Since `MsBackendHdf5Peaks` stores almost everything in-memory expect `mz` and `intensity` (on-disk), the `modCount` values will only be changed/increased while having writing operations on `mz` and `intensity`, such as `backendInitialize` and `replaceList`. `replaceList` is also used in `setReplaceMethod,intensity` and `setReplaceMethod,mz"` and `setReplaceMethod,asDataFrame`.

So when it comes to `MsBackendSql`, it's inevitable to extend the writing functions to other columns besides `mz` and `intensity`, e.g `setReplaceMethod,$`. Then the `modCount` value in `MsBackendSql` shall also be applied to other columns such as `msLevel`. I hope my understanding about `modCount` is correct here.

For the current values in `.attach_migration`, it shall be "x@modCount <- x@modCount + 1L", since we will only append `y.dbtable` to `x`. Hence it's just one writing operation here for `x`. The extra DB operations over instance `y` can always be checked on `y` itself.

2020-08-04 18:35 UTC, plantton commented on R/MsBackendSqlDb-functions.R
>          x@modCount <- unlist(c(x@modCount, y@modCount),
I think I also have to store a  `modCount` value in SQLite database as well. I will set this value when create the writing functions.

2020-08-05 05:20 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
>          x@modCount <- unlist(c(x@modCount, y@modCount),
Yes, you are right. You have to increment the `modCount` each time you update/change any column in the database (`x@modCount <- x@modCount + 1L`) - for subsetting you don't need to do that. Also, each time you increment `modCount` you have also to update the value for this in the database.

The line `x@modCount <- unlist(c(x@modCount, y@modCount))` is however wrong as this would lead to have a `modCount` of length 2. You should change that to `x@modCount <- max(x@modCount, y@modCount) + 1L` to increment the value when you combine databases and also write this value back into the database.

In addition, make sure you have a helper function that compares the `@modCount` with the respective value in the database and throws an error when that's not the case. That function might have to be called in each data access call.

2020-08-05 06:17 UTC, plantton commented on R/MsBackendSqlDb-functions.R
>          x@modCount <- unlist(c(x@modCount, y@modCount),
Ok, I see. I will modify it to `x@modCount <- max(x@modCount, y@modCount) + 1L`.

2020-08-19 12:36 UTC, jorainer approved these changes
I'm OK with this PR, great work @plantton !

2020-08-19 13:46 UTC, plantton commented
> I'm OK with this PR, great work @plantton !

Thank you. But just wait one more day, I still have to fix the comments from the other split PR #17. I want to use the current stable version for a short demo tomorrow. @lgatto

2020-08-20 12:39 UTC, merged