Solving the issues in small PR #17
rformassspectrometry/Deprecated-MsBackendSql pull request #21
Opened 2020-08-24 07:19 UTC by plantton

- Remove redundant `return` functions  
- Add an `IF` statement to function `.attach_migration`: Only working for SQLite connections now.

2020-08-24 13:09 UTC, lgatto requested changes

2020-08-24 13:09 UTC, lgatto commented on NEWS.md
> +Changes in 0.5.0
The version here is wrong. If you want to change the version number, it should be the last one, and this needs also be done in the `DESCRIPTION` file.

2020-08-24 13:09 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +        x
I prefer to keep `return()` here, as it makes clear that the function can return in the middle of its body.

2020-08-24 13:09 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +      x
Same as above.

2020-08-24 13:09 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +        objects[[1]]
Same as above.

2020-08-24 13:09 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +        res
Same as above.

2020-08-24 13:09 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +        res
Here no `return()` is fine.

2020-08-24 13:09 UTC, lgatto commented on R/MsBackendSqlDb.R
> +    output
Here no `return()` is fine.

2020-08-24 13:09 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +        x} else {
Please leave `return()` here.

2020-08-24 13:09 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +        x } else if (identical(x@dbcon@dbname, y@dbcon@dbname) &&
Please leave `return()` here.

2020-08-24 13:09 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +        x } else if (identical(x@dbcon@dbname, y@dbcon@dbname) &&
Add a new line before `} else ...`

2020-08-24 13:09 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +        x} else {
Add a new line before `} else ...`

2020-08-24 13:15 UTC, plantton commented on NEWS.md
> +Changes in 0.5.0
Ok. I will check it.

2020-08-24 13:49 UTC, plantton commented on NEWS.md
> +Changes in 0.5.0
> The version here is wrong. If you want to change the version number, it should be the last one, and this needs also be done in the `DESCRIPTION` file.

I changed the current version to `0.5.0` in commit [02c29cc](https://github.com/rformassspectrometry/MsBackendSql/pull/21/commits/02c29cc5ea47c423dea4d46310a081be774f89e0).

2020-08-24 14:08 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +        x
> I prefer to keep `return()` here, as it makes clear that the function can return in the middle of its body.

modified in commit [277facd](https://github.com/rformassspectrometry/MsBackendSql/pull/21/commits/277facd25cdc215966146f54dcc1b344f8562eb7).

2020-08-24 14:08 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +      x
> Same as above.

modified in commit [277facd](https://github.com/rformassspectrometry/MsBackendSql/pull/21/commits/277facd25cdc215966146f54dcc1b344f8562eb7).

2020-08-24 14:08 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +        objects[[1]]
> Same as above.

modified in commit [277facd](https://github.com/rformassspectrometry/MsBackendSql/pull/21/commits/277facd25cdc215966146f54dcc1b344f8562eb7).

2020-08-24 14:08 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +        res
> Same as above.

modified in commit [277facd](https://github.com/rformassspectrometry/MsBackendSql/pull/21/commits/277facd25cdc215966146f54dcc1b344f8562eb7).

2020-08-24 14:08 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +        res
> Here no `return()` is fine.

modified in commit [277facd](https://github.com/rformassspectrometry/MsBackendSql/pull/21/commits/277facd25cdc215966146f54dcc1b344f8562eb7).

2020-08-24 14:09 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +        x} else {
modified in commit [277facd](https://github.com/rformassspectrometry/MsBackendSql/pull/21/commits/277facd25cdc215966146f54dcc1b344f8562eb7).

2020-08-24 14:09 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +        x } else if (identical(x@dbcon@dbname, y@dbcon@dbname) &&
modified in commit [277facd](https://github.com/rformassspectrometry/MsBackendSql/pull/21/commits/277facd25cdc215966146f54dcc1b344f8562eb7).

2020-08-26 07:41 UTC, lgatto commented
The commit for the `reset()` method looks good to me. Let's wait for a review by @jorainer

2020-08-26 11:55 UTC, jorainer requested changes
Thanks for the PR @plantton ! Looks great. Only minor comments. And please update/fix the documentation of the `MsBackendSQL` object. It looks like it's still the very first version I wrote. Please update:
- describe what the `reset` method does. This is something that other backends can't do (i.e. undo row filtering).
- provide some background information, such as where the data is stored, what data is kept in memory etc.
- add yourself as author

2020-08-26 11:55 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +    slot(x, "rows", check = FALSE) <- 1L:rowNum[1, 1]
Please try to use `seq_along`, `seq_len` etc instead of  `1:` wherever possible (what if your table is empty? you would get `1:0` although `rows` should then be `integer(0)`). Please use `seq_len(rowNum[1, 1])` instead.

2020-08-26 11:55 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +    ## We fetch the number of rows for SQLite table
Also, comments are nice, but here they are just too much because it is easily possible to understand what you are doing from the code itself. Try to use only comments in the code if absolutely necessary.

2020-08-26 13:32 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +    slot(x, "rows", check = FALSE) <- 1L:rowNum[1, 1]
Thank you. That's a very good point!

2020-09-04 16:30 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +    ## We fetch the number of rows for SQLite table
Comments shouldn't explain what the code does. The code should be self-explanatory; if it isn't, it's a sign that it should be improved. Comments should explain why things work in a certain way, focus on the higher level logic, explain some side effects that aren't obvious from the code itself, ...

2020-09-04 16:30 UTC, lgatto commented
@plantton - have @jorainer's points been addressed?

2020-09-25 05:20 UTC, jorainer reviewed
I think you addressed all points regarding the code and the functionality @plantton , but you still need to update/extend the documentation of your backend (*MsBackendSqlDb.R* file lines 4-91. Please check if the text is still valid and correct/expand accordingly.

2020-09-25 08:38 UTC, plantton commented
> I think you addressed all points regarding the code and the functionality @plantton , but you still need to update/extend the documentation of your backend (_MsBackendSqlDb.R_ file lines 4-91. Please check if the text is still valid and correct/expand accordingly.

I will try to improve the documents in the following days. And I also think it has to be adjusted to the latest version of `Spectra`.

2020-09-25 11:38 UTC, jorainer commented
Great. When you're done please re-request me to review - so I know I should check it again.

2020-09-26 10:41 UTC, lgatto requested changes

2020-09-26 10:41 UTC, lgatto commented on NEWS.md
> +## Changes in 0.5.1
The 0.5.1 section much come above 0.5.0

2020-10-27 19:04 UTC, lgatto commented
The vignette fails to build with
```
Quitting from lines 61-65 (MsBackendSqlDb.Rmd) 
Error: Error: processing vignette 'MsBackendSqlDb.Rmd' failed with diagnostics:
unused argument (dbcon = conn)
--- failed re-building ‘MsBackendSqlDb.Rmd’
```

2020-10-27 20:44 UTC, plantton commented
> The vignette fails to build with
> 
> ```
> Quitting from lines 61-65 (MsBackendSqlDb.Rmd) 
> Error: Error: processing vignette 'MsBackendSqlDb.Rmd' failed with diagnostics:
> unused argument (dbcon = conn)
> --- failed re-building ‘MsBackendSqlDb.Rmd’
> ```

Yes. I'm still reviewing all the functions.

2020-12-06 16:45 UTC, merged