Reading functionalities for MsBackendSql
rformassspectrometry/Deprecated-MsBackendSql pull request #6
Opened 2020-05-20 18:30 UTC by plantton

2020-05-25 16:40 UTC, lgatto reviewed
I am starting the review. Here are a few comments to start with:
- The following files should not have been removed: `.Rbuildignore`, `.gitignore` and `.editorconfig`. Could you please add them back.
- I have deleted the html vignette. There should never be included in the source package.

2020-05-25 16:41 UTC, lgatto commented
@jorainer - feel free of course to also participate in the code review.

2020-05-25 16:47 UTC, lgatto commented on MsBackendSql.Rproj
> +Version: 1.0
We generally do not put any RStudio files in the repo (mainly because non of @jorainer @sgibb and myself use RStudio). Please remove it and add it to `.gitignore` so that you can keep using it locally.

2020-05-25 16:51 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +.SPECTRA_DATA_COLUMNS <- c(
@plantton - are these the same ones as defined in `MsBackend`? I think we should avoid duplicating these in different packages at all costs. 

@jorainer - should we go for `Spectra:::.SPECTRA_DATA_COLUMNS` to use it in external packages, or should we consider exporting either the variable, or a function that returns the column names? I could imagine a situation were different packages use all of them, a subset only, or even adds new variables, and that function could be a centralised way to manage such situations.

2020-05-25 16:53 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +            flds <- c(flds, `pkey` = "INTEGER PRIMARY KEY")
I imagine @jorainer used `_pkey` here to make it less likely to have a name clash. Could you confirm, @jorainer, and comment on whether to prefix it with a `_`.

2020-05-25 17:25 UTC, lgatto requested changes
I will look at the code and vignette in more details in the coming days.

2020-05-25 17:25 UTC, lgatto commented on .github/workflows/check-standard.yaml
> -on:
Why have the github workflow files been deleted? I think we can use these instead of travis - it's a nice test. So either put the workflow files back or, if you want to use travis, please add a fully functional travis config file.

2020-05-25 17:25 UTC, lgatto commented on .travis.yml
> +# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
See comment re github workflow files.

2020-05-25 17:25 UTC, lgatto commented on R/peaks-functions-SQL.R
> +.peaks_is_centroided <- function(x, spectrumMsLevel, centroided = NA,
Is this the same one as in `Spectra:::.peaks_is_centroided()`? Please do not copy/paste code from other packages (without attribution), but rather reuse the function directly. And I am wondering if it isn't rather the exported `isCentroided` that should be used instead.

2020-05-25 17:25 UTC, lgatto commented on inst/ext/vignette/bench_RAM.Rmd
> +save(peakram1, peakram10, peakram20,
The vignette shouldn't save that file; at least is isn't needed. 

If saving a file is necessary as part of the vignette, then it should be saved in a temporary file (see `tempfile()`) so that it doesn't pollute the package. 

If a data file is needed in the vignette (for example a pre-computed object to save time), then in should be prepared and saved in `./data` (in which case it will be publicly available and should be documented) or `./inst/extdata` (for private use only).

2020-05-25 17:25 UTC, lgatto commented on .Rbuildignore
> -.editorconfig
Could you please add this file back. It is important.

2020-05-25 17:25 UTC, lgatto commented on .editorconfig
> -# top-most EditorConfig file
Could you please add this file back. It is important.

2020-05-25 17:25 UTC, lgatto commented on .gitignore
> -docs
Could you please add this file back. It is important.

2020-05-25 17:25 UTC, lgatto commented on .travis.yml
> +# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
See my comment re workflow vs travis above.

2020-05-25 17:25 UTC, lgatto commented on MsBackendSql.Rproj
> +Version: 1.0
We generally don't use a .RStudio file, given that neither of @jorainer @sgibb nor me use RStudio. Could you please remove it from git, but add it the `.gitignore` file so you can use it locally.

2020-05-26 09:07 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +            flds <- c(flds, `pkey` = "INTEGER PRIMARY KEY")
Yes, I used `"_pkey"` because chances are that users might have a spectra variable `"pkey"` but it's less likely they would use `"_pkey"`. I'm OK with both versions, but if we use `"pkey"` we have to clearly state somewhere that this is a *reserved* variable name and users should avoid naming one column with that.

2020-05-26 09:08 UTC, jorainer commented on .github/workflows/check-standard.yaml
> -on:
I would opt for the github workflow files. They allow testing the package with different operating systems and specific R versions.

2020-05-26 09:21 UTC, plantton commented on .github/workflows/check-standard.yaml
> -on:
I will add the github workflow files back.

2020-05-26 09:24 UTC, jorainer requested changes
Nice PR @plantton ! Great work! I have some change requests/suggestions but otherwise I think we're on the right way.

2020-05-26 09:24 UTC, jorainer commented on R/MsBackendSqlDb.R
> +getDBcon <- function(x) {
Generally, Bioconductor packages have a `dbconn` method to access database connections. I would rather use that, if et al (see previous post).

2020-05-26 09:24 UTC, jorainer commented on R/MsBackendSqlDb.R
> +getDBtable <- function(x) {
Do we really want to export all these methods? The *normal* user should not directly call functions/methods of the `MsBackend` object, so, unless there is a clear reason for that, I would not export any functions/methods other than the one which are defined for the `MsBackend` class.

The `MsBackend` classes are supposed to be hidden from the normal usage, users should only work with the `Spectra` object. Also, it can be confusing to have functions you can call on an `MsBackendSql` which are not available for e.g. a `MsBackendDataFrame`.

So, I would suggest to keep all these functions (`getDBcon`, `getModCount`...) as internal functions, to call them e.g. `".getDBtable"`, i.e. with a leading `"."` to make it explicit that they are for internal use only and eventually also use `getDbTable` instead of `getDBtable`.

2020-05-26 09:24 UTC, jorainer commented on DESCRIPTION
> +    dplyr,
for what are you using the `dbplyr` package? If it's only used in unit tests and/or examples I would remove it to keep dependencies as small as possible.

2020-05-26 09:24 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +.SPECTRA_DATA_COLUMNS <- c(
Hm, for now I would use `Spectra:::.SPECTRA_DATA_COLUMNS` but I agree, it makes sense to have an accessor function for this in the `Spectra` package.

2020-05-26 09:56 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +            flds <- c(flds, `pkey` = "INTEGER PRIMARY KEY")
To be on the safe side, let's use `_pkey` and specify that it is a reserved variable name. What I also like with the leading underscore is that it is immediately clear, from the weird name, that there's something special about that variables.

2020-05-26 09:57 UTC, lgatto commented on R/MsBackendSqlDb.R
> +getDBtable <- function(x) {
I fully agree, thank you Jo.

2020-05-26 09:59 UTC, lgatto commented on R/MsBackendSqlDb-functions.R
> +.SPECTRA_DATA_COLUMNS <- c(
Ok for direct access with `Spectra:::.SPECTRA_DATA_COLUMN` then.

2020-06-04 16:00 UTC, plantton commented on R/peaks-functions-SQL.R
> +.peaks_is_centroided <- function(x, spectrumMsLevel, centroided = NA,
For the method `isCentroided` in `MsBackendSql`, I created another `as.list` function using the the two `mz()` and `intensity()` functions for `MsBackendSql`. So I will use `Spectra:::.peaks_is_centroided()` here.

2020-06-05 19:23 UTC, plantton commented on DESCRIPTION
> +    dplyr,
> for what are you using the `dbplyr` package? If it's only used in unit tests and/or examples I would remove it to keep dependencies as small as possible.

I think I have to add `dplyr` into `Suggests:` to keep the warnings away. But do you suggest me to use other codes instead of `dplyr` to reshape my script?

2020-06-08 06:05 UTC, jorainer commented on DESCRIPTION
> +    dplyr,
Where are you using `dplyr` code? If it's in the unit tests, examples and/or vignette I would suggest to replace the `dplyr` code with alternative code.

2020-06-08 06:24 UTC, jorainer requested changes
Thanks for the update @plantton ! Still some minor things, but I really like the PR!

2020-06-08 06:24 UTC, jorainer commented on tests/testthat/test_MsBackendSqlDb.R
> +    expect_equal(gsub("\\\\", "/", dataOrigin(test_be)),
Alternatively you could use `normalizePath(dataOrigin(test_be)), normalizePath(dataOrigin(b1))` - but I've not tested if that works...

2020-06-08 06:24 UTC, jorainer commented on .github/workflows/check-standard.yaml
>            - {os: windows-latest, r: '3.6'}
Wouldn't it be better to use `r: '4.0'` here and below, i.e. use R 4 instead of R 3.6?

2020-06-08 06:24 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +    stopifnot(inherits(x, "MsBackendSqlDb"))
I would remove these `stopifnot` calls here and for all other internal functions below. These functions are supposed to be called only **within** this package and thus there should be no need to check that `x` is of the correct type. In general, internal functions should be as fast as possible, thus, you avoid to perform too much input argument checking. Functions that are exported and are supposed to be used by the user yes, there you need to perform input argument checkings.

2020-06-08 08:51 UTC, lgatto commented on .github/workflows/check-standard.yaml
>            - {os: windows-latest, r: '3.6'}
Yes, definitely.

2020-06-09 09:43 UTC, sgibb requested changes
Thanks for this PR.
I am sorry but I have a lot of questions/change requests.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb-functions.R
> +    if (!is.null(msg))
I don't understand the two lines above: `msg` (which is a poor variable name here) will always be `FALSE` (column names should be never `NULL` in that case, if there is no difference `setdiff` will return `character(0)`).

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb-functions.R
> +            ncol1 <- length(set_diff)
These two lines are more or less the same as you did before the `if`.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb-functions.R
> +    hdr <- cbind(hdr, df1)
IMHO the whole stuff above could be replaced by
```r
hdr[, setdiff(names(Spectra:::.SPECTRA_DATA_COLUMNS), names(hdr))] <- NA 
# or NA_real_, NA_character_ depending on the class we need later
```

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb-functions.R
> +    stopifnot(inherits(x, "MsBackendSqlDb"))
Isn't an internal function that just returns a slot useless at all? I would remove that `.getDbTable` function.

EDIT: And I also would remove all the internal getter functions below that just return a slot.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb-functions.R
> +.replace_db_table_columns <- function(object, column, value) {
Could you please explain this function a little bit more? Why we don't use `ALTER TABLE dbtable ALTER COLUMN column columntype` for this? And do we really want to change the datatype of a column later (after the initial import)?

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +#' accessed or changed by the user, which can be retrieved by `getter`
IMHO the slots should not be available to the user.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +                               rows = integer(0),
that's the same as before

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +  msg <- .valid_db_table_columns(object@dbcon, object@dbtable)
This will be overwritten by the PR #8 anyway but please use 4 spaces for indentation.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +            if (missing(dbcon) || !dbIsValid(dbcon))
It seems RStudio doesn't support `.editorconfig` so you have to take care for indentation etc. As above please use 4 spaces and don't just change spaces.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +    msg <- .valid_db_table_has_columns(object@dbcon,
You don't have to check for this column manually. It is done while initialize the whole `MsBackendSqlDb` object.

And IMHO `.get_db_data` should return `NULL`/`FALSE` or something if an SQL error occurs (e.g. missing column). The validation function checks a lot of columns and would just cause additional/expensive workload. Also it is error prone to test for the column manually every time you want to access them. (I added a comment there.)

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +    msg <- .valid_db_table_has_columns(object@dbcon,
As above for `intensity`.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb-functions.R
>                                " from ", object@dbtable, " where _pkey = ?"))
IMHO `.get_db_data` should return `NULL`/`FALSE` or something if an SQL error occurs (e.g. missing column).

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +    msg <- .valid_db_table_has_columns(object@dbcon,
As above for `intensity`.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +            df_columns <- intersect(columns, dbfields)
Why these 3 lines above are necessary. IMHO `.get_db_data(object, columns)` should be enough.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +            other_columns <- setdiff(columns, dbfields)
I don't understand why you first look for common columns in the database and in a second step for the diff columns? Beside I don't understand why you want columns that the user not asked for this seems to be redundant.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +            res[, columns, drop = FALSE]
After fetching `other_columns` which might be expensive in memory you now drop them again?
As mentioned above I guess the whole function could be replaced by a `.get_db_data` call. BTW  `.get_db_data` already does the whole `NumericList` stuff for `mz` and `intensity`.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +    }   else vapply1d(intensity(object), sum, na.rm = TRUE)
What happens for `initial = FALSE`?

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +      if (any(dbListFields(object@dbcon, object@dbtable) == "totIonCurrent"))
As already mentioned IMHO `.get_db_data` should handle a missing column correctly. It shouldn't be necessary to test it here.

2020-06-09 09:43 UTC, sgibb commented on R/MsBackendSqlDb.R
> +    if (!is.null(.valid_db_table_has_columns(x@dbcon,
As already mentioned IMHO `.get_db_data` should handle a missing column correctly. It shouldn't be necessary to test it here.

2020-06-09 11:01 UTC, jorainer commented on R/MsBackendSqlDb-functions.R
> +.replace_db_table_columns <- function(object, column, value) {
Little explanation: `ALTER TABLE` for SQLite does only support renaming a table or adding a column. It does not support deleting a column or changing it's type. Basically, what we wanted to have here is the same/similar functionality that we would have with a `DataFrame`, i.e. add columns, delete columns, change the type of the column. All this is required for the backend to completely support the `MsBackend` interface. Because we need to allow users to delete a column `sps$not_wanted <- NULL`, add a column `sps$new_column <- 1L` and change the type of the data in that column `sps$new_column <- "a"`.

2020-06-15 15:49 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +    if (!is.null(msg))
> I don't understand the two lines above: `msg` (which is a poor variable name here) will always be `FALSE` (column names should be never `NULL` in that case, if there is no difference `setdiff` will return `character(0)`).

I have modified the two lines. Thanks for report.

2020-06-15 15:50 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +    stopifnot(inherits(x, "MsBackendSqlDb"))
Since we haven't created the subsetting and writing functions yet. I will just keep these getters right now. If they're redundant, I will remove them in the following development.

2020-06-15 15:54 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +    hdr <- cbind(hdr, df1)
Thank you. I have replaced the whole block with the new codes.

2020-06-15 15:57 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +.replace_db_table_columns <- function(object, column, value) {
> Could you please explain this function a little bit more? Why we don't use `ALTER TABLE dbtable ALTER COLUMN column columntype` for this? And do we really want to change the datatype of a column later (after the initial import)?

This function will be used to replace one column in the SQLite backend. Now it's a demo to test the SQLite capacity to replace the column, since there're some limitations of SQLite itself (`ALTER TABLE` doesn't support renaming a table or adding new columns.) So the method will create two SQLite `View`s from the original table, then append the newly created column to the `View`.  It's much faster than change all entries within a column on the original column. But I hope I can improve it in the final version.

2020-06-15 20:33 UTC, plantton commented on R/MsBackendSqlDb.R
> +getDBcon <- function(x) {
I removed `getDBcon` function, since there's a `dbconn` method to access the database.

2020-06-15 20:34 UTC, plantton commented on R/MsBackendSqlDb.R
> +getDBtable <- function(x) {
I kept these getters for this moment, since we haven't yet had writing and subsetting functions now.
If it's necessary to remove them, I can delete them in the following development.

2020-06-15 20:35 UTC, plantton commented on DESCRIPTION
> +    dplyr,
I removed all the codes depending on `dplyr` and removed `dplyr` from the `DESCRIPTION` file.

2020-06-15 20:41 UTC, plantton commented on R/MsBackendSqlDb.R
> +            if (missing(dbcon) || !dbIsValid(dbcon))
I have checked all my indentations. But in future, I will adapt to emacs as well.

2020-06-15 20:43 UTC, plantton commented on R/MsBackendSqlDb.R
> +    msg <- .valid_db_table_has_columns(object@dbcon,
I removed all the checking steps within accessors. And add a warning string for missing columns in `.get_db_data` function. I'm also wondering what kind of errors can we expect from the SQLite database? It seems that the users can have their own flexibility to store any random information for the spectrum.

2020-06-15 20:44 UTC, plantton commented on R/MsBackendSqlDb.R
> +    msg <- .valid_db_table_has_columns(object@dbcon,
Solved as `intensity`.

2020-06-15 21:06 UTC, plantton commented on R/MsBackendSqlDb.R
> +    msg <- .valid_db_table_has_columns(object@dbcon,
Solved as `intensity`.

2020-06-15 21:14 UTC, plantton commented on R/MsBackendSqlDb.R
> +            df_columns <- intersect(columns, dbfields)
The function actually mimic the same function `asDataFrame` in [`MsBackendDataFrame`](https://github.com/rformassspectrometry/Spectra/blob/33ad5d10c78f0c7315cf6550445c5bb84ee11686/R/MsBackendDataFrame.R#L412-L432). I think for `spectraVariables`, we have to let the users to decide which variables can be written into the backend. So the columns stored in SQLite database might be different than the columns here. 
But since the writing functionality has been implemented yet. I'm also curious how to keep this flexibility for the users.

2020-06-16 07:59 UTC, lgatto commented on R/MsBackendSqlDb.R
> +            df_columns <- intersect(columns, dbfields)
No, the `spectraVariables` simple returns the available variables. The manual page says
```
        • ‘spectraVariables’: returns a ‘character’ vector with the
          available spectra variables (columns, fields or attributes)
          available in ‘object’.
```

2020-06-16 09:10 UTC, lgatto commented on R/MsBackendSqlDb.R
> +            df_columns <- intersect(columns, dbfields)
As far as I understand, the `asDataFrame,MsBackendSqlDb` method should simply
1. check that the `columns` are valid, i.e. present in the `SQLite` file (the `dbListField` variable above). If not, throw an error.
2. use `.get_db_data(object, columns)` to return the `DataFrame`.

I don't think all the extra code (the ` if (length(other_columns)) ...`) is needed in this case given that all the data is in `SQLite` file, and nowhere else.

2020-06-16 13:58 UTC, plantton commented on R/MsBackendSqlDb.R
> +            df_columns <- intersect(columns, dbfields)
Original function of `asDataFrame` has been removed, and the whole block is replaced with `get_db_data(object, columns)`. The checking of missing columns will be done by `get_db_data`, so there's no checking steps for the `asDataFrame`.

2020-06-16 13:58 UTC, plantton commented on R/MsBackendSqlDb.R
> +            other_columns <- setdiff(columns, dbfields)
The whole block has been removed.

2020-06-16 13:58 UTC, plantton commented on R/MsBackendSqlDb.R
> +            res[, columns, drop = FALSE]
All the block has been removed.

2020-06-16 13:59 UTC, plantton commented on R/MsBackendSqlDb.R
> +      if (any(dbListFields(object@dbcon, object@dbtable) == "totIonCurrent"))
The testing is removed.

2020-06-16 13:59 UTC, plantton commented on R/MsBackendSqlDb.R
> +    if (!is.null(.valid_db_table_has_columns(x@dbcon,
Validation has been removed here.

2020-06-16 15:01 UTC, plantton commented on R/MsBackendSqlDb.R
> +    }   else vapply1d(intensity(object), sum, na.rm = TRUE)
When `initial` is `FALSE`, the `tic` function will calculate total ion current on the actual spectrum data (i.e. `vapply1d` function to sum over all intensity values).
I also compared the two `tic` functions from both `MsBackendSql` and `MsBackendDataFrame`. The returning values are the same.
https://github.com/plantton/MsBackendSql/blob/master/tests/testthat/test_MsBackendSqlDb.R#L145-L149

2020-06-16 15:13 UTC, plantton commented on R/MsBackendSqlDb-functions.R
> +            ncol1 <- length(set_diff)
The whole block has been modified.

2020-06-17 20:31 UTC, plantton commented
Summary of Revised PR `6#` of `MsBackendSql`:  
1. Configurations:  
    - `Rbuildignore`, `.gitignore` and `.editorconfig` are added back.  
	- `RStudio` file: `*.Rproj` is removed.  
	- `GitHub Actions: Workflow` is used instead of `travis-ci`.  
	- `dplyr` is removed from dependencies from the package.  
	- The configuration of `workflow` has been [set](https://github.com/plantton/MsBackendSql/tree/master/.github/workflows).  
	- Indentions are all checked and modified. I will try to adapt to emacs.  
2. Internal functions, such as `Spectra:::.SPECTRA_DATA_COLUMNS` is used to replace `SPECTRA_DATA_COLUMNS`. Another replaced function is `.peaks_is_centroided`.  
3. Primary key: `_pkey` is used instead of `pkey`, regarding any potential misusage by users.  
4. All the getters functions are preserved. I checked the implementation of `SQLDataFrame`, these getters might be useful for our subsetting/filtering [functions](https://github.com/Bioconductor/SQLDataFrame/blob/2d4032cc544c81aada409e3b17c2ebba3c631e18/R/SQLDataFrame-methods.R#L213-L243). But `getDbcon` is removed, since we can use `dbconn`.  
6. Function `.replace_db_table_columns` will be [preserved](https://github.com/rformassspectrometry/MsBackendSql/pull/6#discussion_r440280059). It's a draft version of changing/replacing columns in SQLite database. And I think it's much faster than the ordinary `ALTER` operation.  
7. Function `tic` is [compared with](https://github.com/rformassspectrometry/MsBackendSql/pull/6#discussion_r437277600) `tic` from `MsBackendDataFrame`.  
8. Bugs corrected: 
    - [`.write_mzR_to_db`](https://github.com/plantton/MsBackendSql/blob/master/R/MsBackendSqlDb-functions.R#L79-L92). [Bug1](https://github.com/rformassspectrometry/MsBackendSql/pull/6#discussion_r437227036)  
	- All the checking steps of accessors are removed. The checkings will only be done within `.get_db_data` (see below). [bug2](https://github.com/rformassspectrometry/MsBackendSql/pull/6#discussion_r437245324)  
	- `asDataFrame` is changed, and only use `.get_db_data` for reading back `DataFrame`.  
9. I add a checking step for `.get_db_data`. It will test missing columns and returning a message if there's an error. More testing steps will be added during the development of subsetting and filter.  
10. Vignette: The current vignette has been moved to `Spectra_benchmarking' repository.

2020-06-26 12:29 UTC, lgatto commented on tests/testthat/test_MsBackendSqlDb-functions.R
> +fl <- msdata::proteomics(full.names = TRUE)[4]
Please use the `pattern` argument and not the index, that is likely to change when new files are added.

2020-07-01 11:19 UTC, merged